version: 1
update_configs:
  - package_manager: python
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "backlog-dependencies"
      - "task"
      - "dependencies"
      - "dependabot"
