name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        timeout-minutes: 15
        with:
          ref: 'refs/heads/main'
          running-workflow-name: 'Publish to PyPI'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.5'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Upgrade setuptools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
