---
name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  package:
    needs: [markdownlint-cli, yamllint]
    runs-on: ubuntu-latest
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - run: make package
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_API_TOKEN }}
