---
name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.4.0
        timeout-minutes: 15
        with:
          ref: 'refs/heads/main'
          running-workflow-name: 'Publish to PyPI'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '1.4.1'

      - name: Install dependencies
        run: poetry install --without test

      - name: Publish distribution to PyPI
        run: poetry publish --build -u __token__ -p '${{ secrets.PYPI_API_TOKEN }}'
