---
name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  wait-for-ci:
    name: Wait for CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI to pass
        uses: lewagon/wait-on-check-action@v1.6.1
        with:
          ref: ${{ github.sha }}
          running-workflow-name: Wait for CI
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  publish:
    name: Publish to PyPI
    needs: wait-for-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: '1.4.1'

      - name: Install dependencies
        run: poetry install --without test

      - name: Publish distribution to PyPI
        run: poetry publish --build -u __token__ -p '${{ secrets.PYPI_API_TOKEN }}'
