---
name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 'pypy3'
      - run: make package
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: pypi-AgEIcHlwaS5vcmcCJDY5ZmMwMThhLWViOTItNGU4OC1hZWI0LWI0OWM2NWViMzVhMgACOXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJkbnNpbXBsZSJdfSwgInZlcnNpb24iOiAxfQAABiBxIg9GQ3NEmoUPiE34HHVEBfL9rIUrolvatwpAn1SMPA
