---
name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 'pypy3'
      - name: Install dependencies
        run: >-
          python -m pip install --user --upgrade setuptools wheel
      - name: Build
        run: >-
          python setup.py sdist bdist_wheel
      - run: Publish distribution to PyPI
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
